<a href="https://colab.research.google.com/github/parksuejin1026/2025-1-2-OSS/blob/main/Week6/BDA_week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('/content/2016년졸음운전.csv', encoding = 'euc-kr', index_col = 0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [2]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [4]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [5]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [6]:
df.sum() # 열 별로 총합

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [7]:
df.sum(axis = 0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [8]:
df.sum(axis = 1) # 행마다 총 합

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [9]:
df.cumsum(axis = 0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [10]:
df.cumsum(axis = 1) # 누적 합계를 구하는 함수

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [11]:
df.mean() # 기본적인 axis = 0 임 따라서 열끼리 계산

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [12]:
df.mean(axis = 1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [13]:
df.mean(axis = None) # 전체 평균

np.float64(206.38888888888889)

In [14]:
df.min() # 각 열의 최솟값

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [15]:
df.min(axis = 1) # 각 행의 최솟값

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [17]:
df.min(axis = None) # 모든 데이터 중 최솟값

4

In [18]:
df.max() # default 는 axis = 0

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [19]:
df.max(axis = 1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [20]:
df.max(axis = None)

522

In [23]:
df[['사망(명)', '부상(명)']].sum(axis = 1) # 행 마다의 사망, 부상 명의 합을 구하기

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [24]:
df.iloc[:, 1:].sum(axis = 1) # 전체 행과 , 2번째 열부터 마지막 열의 행 총합

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [26]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis = 1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [29]:
df2.loc['총계'] = df2.sum(axis = 0) # 열들의 총합
df2

           사고(건)  사망(명)   부상(명)    재해자수
연월
2016년1월    192.0    5.0   387.0   392.0
2016년2월    174.0    6.0   328.0   334.0
2016년3월    217.0    7.0   435.0   442.0
2016년4월    216.0    7.0   419.0   426.0
2016년5월    239.0   13.0   522.0   535.0
2016년6월    200.0   12.0   362.0   374.0
2016년7월    227.0    9.0   460.0   469.0
2016년8월    230.0    7.0   490.0   497.0
2016년9월    187.0   13.0   347.0   360.0
2016년10월   183.0   10.0   367.0   377.0
2016년11월   200.0    5.0   418.0   423.0
2016년12월   168.0    4.0   364.0   368.0
총계        2433.0   98.0  4899.0  4997.0

In [30]:
df2 > 10 # true or false 출력

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [31]:
df2[df2 > 10] # 해당하는 값

           사고(건)  사망(명)   부상(명)    재해자수
연월
2016년1월    192.0    NaN   387.0   392.0
2016년2월    174.0    NaN   328.0   334.0
2016년3월    217.0    NaN   435.0   442.0
2016년4월    216.0    NaN   419.0   426.0
2016년5월    239.0   13.0   522.0   535.0
2016년6월    200.0   12.0   362.0   374.0
2016년7월    227.0    NaN   460.0   469.0
2016년8월    230.0    NaN   490.0   497.0
2016년9월    187.0   13.0   347.0   360.0
2016년10월   183.0    NaN   367.0   377.0
2016년11월   200.0    NaN   418.0   423.0
2016년12월   168.0    NaN   364.0   368.0
총계        2433.0   98.0  4899.0  4997.0

In [32]:
df2[ [True] * 6 + [False]  * 7]

         사고(건)  사망(명)  부상(명)   재해자수
연월
2016년1월  192.0    5.0  387.0  392.0
2016년2월  174.0    6.0  328.0  334.0
2016년3월  217.0    7.0  435.0  442.0
2016년4월  216.0    7.0  419.0  426.0
2016년5월  239.0   13.0  522.0  535.0
2016년6월  200.0   12.0  362.0  374.0

In [33]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [34]:
df2[df2['재해자수'] > 400]

           사고(건)  사망(명)   부상(명)    재해자수
연월
2016년3월    217.0    7.0   435.0   442.0
2016년4월    216.0    7.0   419.0   426.0
2016년5월    239.0   13.0   522.0   535.0
2016년7월    227.0    9.0   460.0   469.0
2016년8월    230.0    7.0   490.0   497.0
2016년11월   200.0    5.0   418.0   423.0
총계        2433.0   98.0  4899.0  4997.0

In [35]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [36]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [37]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350 ) ]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [38]:
df [ df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [40]:
df [ '사망(명)' ].isin([7, 10]) # 사망(명) 열에서 7이나 10이 들어가는 행에 True

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [41]:
df[ df['사망(명)'].isin([7,10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [42]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [45]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [46]:
df = pd.DataFrame({'A' : range(1, 6),
                   'B' : range(6,-3, -2),
                   'C' : range(10, 5, -1),
                   'D clmns' : range(3, -2, -1),
                   'E' : ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [48]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [49]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [50]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [51]:
df.query("E != 'python'")  # E 열의 인덱스가 python이 아니면 전체행 출력

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [53]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [54]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [55]:
df.query(' A > 3 | B > 8' )

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [56]:
df.query(' A > 2 & C < 8 ')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [58]:
df.query(" E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [61]:
df.query('A == "D clmns"')  # 문자열에 빈칸이 있으면 df로 출력

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [62]:
df[df.A == df["D clmns"]] # A 행의 값과 D clmns 행의 값이 같다면 출력

   A  B  C  D clmns     E
1  2  4  9        2  java

In [63]:
s = 'E.str.startswith("g")'  # 조건 추가 : E.str이 g로 시작한다면 이라는 조건을 추가
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [64]:
s = "E.str.endswith('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [65]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [66]:
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java